<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Auth\Middleware\Authenticate as Middleware;
use Illuminate\Support\Facades\App;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param \Illuminate\Http\Request $request
     * @return string|null
     */
    protected function redirectTo($request)
    {
        if (session()->has('locale')) {
            App::setLocale(session()->get('locale'));


        }

        if (!$request->expectsJson()) {
            return route('admin.login');
        }
    }

    public function handle($request, Closure $next, ...$guards)
    {
        if (session()->has('locale')) {
            App::setLocale(session()->get('locale'));
        }
        return parent::handle($request, $next, $guards); // TODO: Change the autogenerated stub

    }
}
